name: Deploy FastAPI to Azure Container App

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug Secret
      run: |
        echo "Length of AZURE_CREDENTIALS: ${#AZURE_CREDENTIALS}"
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}


    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY }}

    - name: Build and push image
      run: |
        IMAGE=${{ secrets.AZURE_CONTAINER_REGISTRY }}/fastapi-app:${{ github.sha }}
        docker build -t $IMAGE .
        docker push $IMAGE

    - name: Deploy to Azure Container App
      run: |
        az containerapp update \
          --name ${{ secrets.AZURE_CONTAINER_APP_NAME }} \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --image ${{ secrets.AZURE_CONTAINER_REGISTRY }}/fastapi-app:${{ github.sha }}
